services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_container
    environment:
      POSTGRES_DB: ecomerce
      POSTGRES_PASSWORD: erick
      POSTGRES_USER: erick
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
