services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb_container
    environment:
      MYSQL_DATABASE: ecomerce
      MYSQL_ROOT_PASSWORD: erick
      MYSQL_USER: erick
      MYSQL_PASSWORD: erick
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
